### ISSUE TITLE
CSS to make catlist look good on mobile?

### ISSUE THREAD

**Issue by gabuzom** [xif-fr/dokuwiki-plugin-catlist#38]
Hello there and thanks for the very useful plugin!

Apparently, on mobile devices the lists appear like if they were very much zoomed, which for multi-column looks very weird and hard to read.. Does anyone know of a right CSS "patch" that would make it look OK on mobile browsers? Maybe making the columns independant floats: or something like this?

Thanks!

**Comment by xif-fr** [comment]
Hi, could you send a screenshot ? I don't have mobile devices to test.

**Comment by WebFreak001** [comment]
here is a style I made which is quite hacky though:
```css
@media screen and (max-width: 1000px) {
  .catlist_columns[style*="column-count:"] {
    padding-left: 0;
  }
}

@media screen and (max-width: 600px) {
  .catlist_columns[style*="column-count:"] {
    -webkit-column-count: 1 !important;
    -moz-column-count: 1 !important;
    column-count: 1 !important;
  }
}
```
the top block removes some padding on the left (so the list items are basically right on the edge of the content) on smaller screens

the bottom block forces all multi-column catlists to be single-column on screens 600px or narrower. (in my pages I use at most 3 columns, which I think is the last one that looks ok at this size)

This CSS must be in a CSS file and can't be assigned through attributes, so you can make it a part of your custom CSS changes, see https://www.dokuwiki.org/faq:css
